<?php /* Template Name: About Us Page */ 

 get_template_part('inc/partials/header'); 
get_header();

while ( have_posts() ) : the_post(); 
?>
<main>
	<div class="container">
<section class="sj-block m-5"><div class="container"><div class="row justify-content-center"><div class="col col-md-8 text-center"><h1>Prototype Blocks</h1><p class="lead"> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris World of Grammar. </p></div></div></div></section>

<section class="sj-block m5"><div class="container"><div class="row"><div class="col text-center"><h1>Prototype Blocks</h1><div class="row text-left pt-4"><div class="col-12 col-md-6"><p class="lead"> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut A small river named Duden flows by their place Lorem ipsum dolor sit amet. </p></div><div class="col-12 col-md-6"><p class="lead"> Lorem ipsum dolor sit amet, consectetur adipiscing elit Lorem ipsum dolor sit amet, consectetur adipiscing , Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Lorem ipsum dolor sit amet, consectetur adipiscing elit right at the coast. </p></div></div></div></div></div></section>

<section class="row sj-block my-5" ><div class="col-xl-3 col-md-6 col-12"><div class="card"><div class="text-center"><div class="card-body"><img alt="Card image" class="rounded-circle  height-150" src="https://via.placeholder.com/150x150"></div><div class="card-body"><h4 class="card-title">Lorem Ipsum Dolar</h4><h6 class="card-subtitle text-muted">Lorem Ipsum Dolar</h6></div><div class="text-center"><a class="btn btn-social-icon mr-1 mb-1 btn-outline-facebook" href="#"><span class="fab fa-facebook"></span></a><a class="btn btn-social-icon mr-1 mb-1 btn-outline-twitter" href="#"><span class="fab fa-twitter"></span></a><a class="btn btn-social-icon mb-1 btn-outline-linkedin" href="#"><span class="fab fa-linkedin font-medium-4"></span></a></div></div></div></div><div class="col-xl-3 col-md-6 col-12"><div class="card"><div class="text-center"><div class="card-body"><img alt="Card image" class="rounded-circle  height-150" src="https://via.placeholder.com/150x150"></div><div class="card-body"><h4 class="card-title">Lorem Ipsum Dolar</h4><h6 class="card-subtitle text-muted">Lorem Ipsum Dolar</h6></div><div class="text-center"><a class="btn btn-social-icon mr-1 mb-1 btn-outline-facebook" href="#"><span class="fab fa-facebook"></span></a><a class="btn btn-social-icon mr-1 mb-1 btn-outline-twitter" href="#"><span class="fab fa-twitter"></span></a><a class="btn btn-social-icon mb-1 btn-outline-linkedin" href="#"><span class="fab fa-linkedin font-medium-4"></span></a></div></div></div></div><div class="col-xl-3 col-md-6 col-12"><div class="card"><div class="text-center"><div class="card-body"><img alt="Card image" class="rounded-circle  height-150" src="https://via.placeholder.com/150x150"></div><div class="card-body"><h4 class="card-title">Lorem Ipsum Dolar</h4><h6 class="card-subtitle text-muted">Lorem Ipsum Dolar</h6></div><div class="text-center"><a class="btn btn-social-icon mr-1 mb-1 btn-outline-facebook" href="#"><span class="fab fa-facebook"></span></a><a class="btn btn-social-icon mr-1 mb-1 btn-outline-twitter" href="#"><span class="fab fa-twitter"></span></a><a class="btn btn-social-icon mb-1 btn-outline-linkedin" href="#"><span class="fab fa-linkedin font-medium-4"></span></a></div></div></div></div><div class="col-xl-3 col-md-6 col-12"><div class="card"><div class="text-center"><div class="card-body"><img alt="Card image" class="rounded-circle  height-150" src="https://via.placeholder.com/150x150"></div><div class="card-body"><h4 class="card-title">Lorem Ipsum Dolar</h4><h6 class="card-subtitle text-muted">Lorem Ipsum Dolar</h6></div><div class="text-center"><a class="btn btn-social-icon mr-1 mb-1 btn-outline-facebook" href="#"><span class="fab fa-facebook"></span></a><a class="btn btn-social-icon mr-1 mb-1 btn-outline-twitter" href="#"><span class="fab fa-twitter"></span></a><a class="btn btn-social-icon mb-1 btn-outline-linkedin" href="#"><span class="fab fa-linkedin font-medium-4"></span></a></div></div></div></div></section>
</div>

<section class="sj-block bg-dark sj-viewport" style="background-image: url(https://via.placeholder.com/430x200);"><div class="container align-items-center justify-content-center d-flex"><div class="row justify-content-center text-center"><div class="col-12 col-md-10 col-lg-8"><h1> Lorem ipsum dolor sit amet </h1><p class="mt-5"><a class="btn btn-outline-light" href="#">Call to Action</a></p></div></div></div></section>
</main >
<?php 
endwhile; 
get_footer(); 
?>